version: '3.8'
services:
  postgres:
    image: postgres:13
    restart: always
    container_name: postgres_db
    ports:
      - "5555:5432"
    environment:
      - POSTGRES_USER=${DATABASE_USER:-postgres}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-postgres}
      - POSTGRES_DB=${DATABASE_NAME:-postgres_db}
    volumes:
      - postgres_db:/var/lib/postgresql/data
volumes:
  postgres_db: